### ISSUE TITLE
Liquidation event

### ISSUE THREAD

**Issue by chronosone** [Abracadabra-money/magic-internet-money#28]
Is there any plan to add Liquidation event to the liquidate function of Caudron?
Now I found the only way to watch the liquidation is subscribe LogRemoveCollateral and LogRepay events, then check if triggered both in the same transaction.

**Comment by 0xCalibur** [comment]
Sorry for the late response, the cauldron already deployed cannot be modified but we will consider adding it for future one. I will discuss the matter with Merlin, thanks for the suggestion
