### ISSUE TITLE
"claim" function in cvx3pool does not show rewards

### ISSUE THREAD

**Issue by asinugobi** [Abracadabra-money/magic-internet-money#53]
I was trying to borrow MIM against cvx3pool coins. After clicking the "claim" button instead of borrowing MIM, the cvx3pool coins disappeared. The resulting stkcvx3Crv-abra tokens are not available in the UI.

Is there a method for unwrapping the stkcvx3Crv-abra tokens?

**Comment by 0xCalibur** [comment]
are you using this pool? https://abracadabra.money/pool/25

"After clicking the "claim" button instead of borrowing MIM"
> The claim button isn't the borrow but to claim cvx3Crv rewards

**Comment by 0xCalibur** [comment]
Closed for innactivity
