### ISSUE TITLE
Bug bounty / responsible disclosure contacts

### ISSUE THREAD

**Issue by WTn5gU5uXPCM** [Abracadabra-money/magic-internet-money#94]
I would like to know if there is an active bug bounty program for Abracadabra or if there is any way to contact the developers/maintainers directly. The link from the website to an Immunefi bug bounty program is 404. If you can direct me to the current bug bounty program or if you can provide dev/maintainer contacts, that can be helpful. You can reach me directly via email here:
WTn5gU5uXPCM [at] proton.me

Thank you!

**Comment by 0xCalibur** [comment]
you can reach me to @Oxcalibur on telegram
